Импортируем датафрейм, убираем ограничение на количество отображённых колонок, и смотрим первые пять строк датафрейма

In [4]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('NBA_Stats_71_Years.xlsx')
pd.set_option('display.max_columns', None)
df.head()

,Rank,Year,Season Start Year,Season Type,Player ID,Player,Team ID,Team,Games Played,Minutes Played,FG Made,FG Attempts,FG %,3-Pt FG Made,3-Pt FG Attempts,3-Pt FG %,FT Made,FT Attempts,FT %,Offensive Rebounds,Defensive Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points Scored,Efficency,AST/TOV,STL/TOV
0,1,1951-52,1951,Regular Season,76056,Paul Arizin,1610612744,PHW,66,2939,548,1222,0.448,NaN,NaN,NaN,578,707,0.818,NaN,NaN,745,170,NaN,NaN,NaN,250,1674,1786,NaN,NaN
1,2,1951-52,1951,Regular Season,600012,George Mikan,1610612747,MNL,64,2572,545,1414,0.385,NaN,NaN,NaN,433,555,0.780,NaN,NaN,866,194,NaN,NaN,NaN,286,1523,1592,NaN,NaN
2,3,1951-52,1951,Regular Season,600003,Bob Cousy,1610612738,BOS,66,2681,512,1388,0.369,NaN,NaN,NaN,409,506,0.808,NaN,NaN,421,441,NaN,NaN,NaN,190,1433,1322,NaN,NaN
3,4,1951-52,1951,Regular Season,77429,Ed Macauley,1610612738,BOS,66,2631,384,888,0.432,NaN,NaN,NaN,496,621,0.799,NaN,NaN,529,232,NaN,NaN,NaN,174,1264,1396,NaN,NaN
4,5,1951-52,1951,Regular Season,76514,Bob Davies,1610612758,ROC,65,2394,379,990,0.383,NaN,NaN,NaN,294,379,0.776,NaN,NaN,189,390,NaN,NaN,NaN,269,1052,935,NaN,NaN

Смотрим на типы колонок и количество ненулевых значений в каждой из них

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33330 entries, 0 to 33329
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                33330 non-null  int64
 1   Year                33330 non-null  object
 2   Season Start Year   33330 non-null  int64
 3   Season Type         33330 non-null  object
 4   Player ID           33330 non-null  int64
 5   Player              33330 non-null  object
 6   Team ID             33330 non-null  int64
 7   Team                33330 non-null  object
 8   Games Played        33330 non-null  int64
 9   Minutes Played      33330 non-null  int64
 10  FG Made             33330 non-null  int64
 11  FG Attempts         33330 non-null  int64
 12  FG %                33330 non-null  float64
 13  3-Pt FG Made        27034 non-null  float64
 14  3-Pt FG Attempts    27034 non-null  float64
 15  3-Pt FG %           27034 non-null  float64
 16  FT Made             33330 non-null  int64
 17  FT Attempts         33330 non-null  int64
 18  FT %                33330 non-null  float64
 19  Offensive Rebounds  29101 non-null  float64
 20  Defensive Rebounds  29101 non-null  float64
 21  Rebounds            33330 non-null  int64
 22  Assists             33330 non-null  int64
 23  Steals              29101 non-null  float64
 24  Blocks              29101 non-null  float64
 25  Turnovers           27764 non-null  float64
 26  Personal Fouls      33330 non-null  int64
 27  Points Scored       33330 non-null  int64
 28  Efficency           33330 non-null  int64
 29  AST/TOV             27764 non-null  float64
 30  STL/TOV             27764 non-null  float64
dtypes: float64(12), int64(15), object(4)
memory usage: 7.9+ MB

In [6]:
df.shape

(33330, 31)

Посмотрим статистику игроков "Торонто Рэпторс" в их чемпионский сезон

In [7]:
df.Team.unique()

array(['PHW', 'MNL', 'BOS', 'ROC', 'FTW', 'BAL', 'NYK', 'INO', 'SYR',
       'MIH', 'STL', 'DET', 'CIN', 'LAL', 'CHP', 'SFW', 'CHZ', 'BLT',
       'PHL', 'CHI', 'SEA', 'SDR', 'PHX', 'ATL', 'MIL', 'POR', 'BUF',
       'CLE', 'HOU', 'GOS', 'KCK', 'CAP', 'WAS', 'NOJ', 'DEN', 'IND',
       'SAN', 'NYN', 'NJN', 'SDC', 'UTH', 'DAL', 'LAC', 'SAC', 'CHH',
       'MIA', 'MIN', 'ORL', 'TOR', 'VAN', 'UTA', 'GSW', 'PHI', 'SAS',
       'MEM', 'NOH', 'CHA', 'NOK', 'OKC', 'BKN', 'NOP'], dtype=object)

In [9]:
df = df.rename(columns={
  'Season Start Year':'Season_Start_Year',
  'Season Type':'Season_Type',
  'Player ID':'Player_ID',
  'Team ID':'Team_ID',
  'Games Played':'Games_Played',
  'Minutes Played':'Minutes_Played',
  'FG Made':'FG_Made',
  'FG Attempts':'FG_Attempts',
  'FG %':'FG_per',
  '3-Pt FG Made': 'FG_Made_3Pt',
  '3-Pt FG Attempts':'FG_Attempts_3Pt',
  '3-Pt FG %':'FG_per_3Pt',
  'FT Made':'FT_Made',
  'FT Attempts':'FT_Attempts',
  'FT %':'FT_per',
  'Offensive Rebounds':'Offensive_Rebounds',
  'Defensive Rebounds':'Defensive_Rebounds',
  'Personal Fouls':'Personal_Fouls',
  'Points Scored':'Points_Scored' 
})

Торонто взяли чемпионство в 2019 году, значит сезон начался в 2018

In [10]:
team_tag = "TOR"
Toronto_champ_season = df.query('Season_Start_Year == 2018 & Team == @team_tag')
Toronto_champ_season.head()

,Rank,Year,Season_Start_Year,Season_Type,Player_ID,Player,Team_ID,Team,Games_Played,Minutes_Played,FG_Made,FG_Attempts,FG_per,FG_Made_3Pt,FG_Attempts_3Pt,FG_per_3Pt,FT_Made,FT_Attempts,FT_per,Offensive_Rebounds,Defensive_Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers,Personal_Fouls,Points_Scored,Efficency,AST/TOV,STL/TOV
29507,23,2018-19,2018,Regular Season,202695,Kawhi Leonard,1610612761,TOR,60,2040,560,1129,0.496,112.0,302.0,0.371,364,426,0.854,78.0,361.0,439,199,106.0,24.0,121.0,87,1596,1612,1.65,0.88
29528,44,2018-19,2018,Regular Season,1627783,Pascal Siakam,1610612761,TOR,80,2548,519,945,0.549,79.0,214.0,0.369,237,302,0.785,124.0,425.0,549,248,73.0,52.0,154.0,241,1354,1631,1.61,0.47
29551,67,2018-19,2018,Regular Season,201586,Serge Ibaka,1610612761,TOR,74,2010,464,877,0.529,49.0,169.0,0.290,135,177,0.763,156.0,445.0,601,99,29.0,103.0,114.0,211,1112,1375,0.87,0.25
29556,72,2018-19,2018,Regular Season,201188,Marc Gasol,1610612761,TOR,79,2436,390,870,0.448,99.0,273.0,0.363,192,253,0.759,80.0,547.0,627,349,84.0,86.0,155.0,217,1071,1521,2.25,0.54
29580,96,2018-19,2018,Regular Season,200768,Kyle Lowry,1610612761,TOR,65,2213,304,739,0.411,157.0,453.0,0.347,161,194,0.830,41.0,271.0,312,564,91.0,31.0,182.0,166,926,1274,3.10,0.50

Посмотрим статистику игроков по основным показателям в сезоне

In [11]:
Toronto_champ_season.value_counts('Season_Type')

Season_Type
Regular Season    18
Playoffs          14
dtype: int64

В регулярном сезоне за Торонто играло 18 человек

In [12]:
Toronto_champ_season.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 29507 to 30213
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                32 non-null     int64
 1   Year                32 non-null     object
 2   Season_Start_Year   32 non-null     int64
 3   Season_Type         32 non-null     object
 4   Player_ID           32 non-null     int64
 5   Player              32 non-null     object
 6   Team_ID             32 non-null     int64
 7   Team                32 non-null     object
 8   Games_Played        32 non-null     int64
 9   Minutes_Played      32 non-null     int64
 10  FG_Made             32 non-null     int64
 11  FG_Attempts         32 non-null     int64
 12  FG_per              32 non-null     float64
 13  FG_Made_3Pt         32 non-null     float64
 14  FG_Attempts_3Pt     32 non-null     float64
 15  FG_per_3Pt          32 non-null     float64
 16  FT_Made             32 non-null     int64
 17  FT_Attempts         32 non-null     int64
 18  FT_per              32 non-null     float64
 19  Offensive_Rebounds  32 non-null     float64
 20  Defensive_Rebounds  32 non-null     float64
 21  Rebounds            32 non-null     int64
 22  Assists             32 non-null     int64
 23  Steals              32 non-null     float64
 24  Blocks              32 non-null     float64
 25  Turnovers           32 non-null     float64
 26  Personal_Fouls      32 non-null     int64
 27  Points_Scored       32 non-null     int64
 28  Efficency           32 non-null     int64
 29  AST/TOV             32 non-null     float64
 30  STL/TOV             32 non-null     float64
dtypes: float64(12), int64(15), object(4)
memory usage: 8.0+ KB

In [13]:
Type_of_Season = 'Regular Season'
Tor_reg_stat = Toronto_champ_season.query('Season_Type == @Type_of_Season').iloc[:,[5, 8, 9, 21, 22, 23, 24, 25, 26, 27]]
Tor_reg_stat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18 entries, 29507 to 29987
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Player          18 non-null     object
 1   Games_Played    18 non-null     int64
 2   Minutes_Played  18 non-null     int64
 3   Rebounds        18 non-null     int64
 4   Assists         18 non-null     int64
 5   Steals          18 non-null     float64
 6   Blocks          18 non-null     float64
 7   Turnovers       18 non-null     float64
 8   Personal_Fouls  18 non-null     int64
 9   Points_Scored   18 non-null     int64
dtypes: float64(3), int64(6), object(1)
memory usage: 1.5+ KB

Введём несколько новых признаков, показывающих количество времени, проводимого на площадке в среднем, и эффективность в защите

In [16]:
Tor_reg_stat['STL/FOUL'] = round(Tor_reg_stat.Steals / Tor_reg_stat.Personal_Fouls, 3)
Tor_reg_stat['Avg_minutes'] = round(Tor_reg_stat.Minutes_Played / Tor_reg_stat.Games_Played)

In [17]:
Tor_reg_stat.head()

,Player,Games_Played,Minutes_Played,Rebounds,Assists,Steals,Blocks,Turnovers,Personal_Fouls,Points_Scored,STL/FOUL,Avg_minutes
29507,Kawhi Leonard,60,2040,439,199,106.0,24.0,121.0,87,1596,1.218,34.0
29528,Pascal Siakam,80,2548,549,248,73.0,52.0,154.0,241,1354,0.303,32.0
29551,Serge Ibaka,74,2010,601,99,29.0,103.0,114.0,211,1112,0.137,27.0
29556,Marc Gasol,79,2436,627,349,84.0,86.0,155.0,217,1071,0.387,31.0
29580,Kyle Lowry,65,2213,312,564,91.0,31.0,182.0,166,926,0.548,34.0

In [18]:
Tor_reg_stat.sort_values(by='STL/FOUL', ascending=False)

,Player,Games_Played,Minutes_Played,Rebounds,Assists,Steals,Blocks,Turnovers,Personal_Fouls,Points_Scored,STL/FOUL,Avg_minutes
29507,Kawhi Leonard,60,2040,439,199,106.0,24.0,121.0,87,1596,1.218,34.0
29908,Patrick McCaw,29,397,48,29,23.0,2.0,17.0,38,74,0.605,14.0
29580,Kyle Lowry,65,2213,312,564,91.0,31.0,182.0,166,926,0.548,34.0
29917,Lorenzo Brown,26,212,31,28,12.0,5.0,16.0,22,55,0.545,8.0
29639,Fred VanVleet,64,1760,167,307,57.0,20.0,82.0,110,701,0.518,28.0
29606,Danny Green,80,2215,317,126,73.0,53.0,75.0,171,821,0.427,28.0
29694,Norman Powell,60,1126,139,91,39.0,13.0,65.0,96,516,0.406,19.0
29556,Marc Gasol,79,2436,627,349,84.0,86.0,155.0,217,1071,0.387,31.0
29721,O.G. Anunoby,67,1352,197,47,46.0,22.0,55.0,140,469,0.329,20.0
29636,Jeremy Lin,74,1436,179,231,47.0,13.0,124.0,144,707,0.326,19.0
29528,Pascal Siakam,80,2548,549,248,73.0,52.0,154.0,241,1354,0.303,32.0
29922,Jodie Meeks,8,104,12,8,1.0,1.0,2.0,5,51,0.200,13.0
29942,Malcolm Miller,10,67,5,1,1.0,1.0,1.0,5,35,0.200,7.0
29895,Chris Boucher,28,163,56,2,6.0,24.0,7.0,31,93,0.194,6.0
29551,Serge Ibaka,74,2010,601,99,29.0,103.0,114.0,211,1112,0.137,27.0
29987,Eric Moreland,5,43,20,4,1.0,1.0,5.0,9,7,0.111,9.0
29946,Malachi Richardson,22,103,13,0,1.0,0.0,8.0,13,30,0.077,5.0
29949,Jordan Loyd,12,55,9,6,0.0,0.0,2.0,5,29,0.000,5.0